apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogcat
  template:
    metadata:
      labels:
        app: dogcat
    spec:
      containers:
      - name: dogcat-container
        image: arindam29/dog-cat:ver1
        #imagePullPolicy: Never
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"  # Note: Environment variable values are strings
        resources:
          requests:
            cpu: "500m"
            memory: "2048M"
          limits:
            cpu: "500m"
            memory: "2048M"
      imagePullSecrets:
      - name: my-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dogcat-service
spec:
  selector:
    app: dogcat
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort